<a href="https://colab.research.google.com/github/VijayPnr/DL_Project-Eye_Disease_Prediction/blob/main/Eyedisease_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import cv2
import os                                          #for path & directory

data_path = 'Eye_diseases'                         
categories = os.listdir(data_path)                 #get folder
labels = [i for i in range(len(categories))]       #for getting labels-0,1,2,3,4
label_dict = dict(zip(categories,labels))          #empty directory - combain above 2 lists

print(label_dict)
print(categories)
print(labels)

{'Cataracts': 0, 'Crossed_Eyes': 1, 'Glaucoma': 2, 'Normal': 3, 'Uveitis': 4}
['Cataracts', 'Crossed_Eyes', 'Glaucoma', 'Normal', 'Uveitis']
[0, 1, 2, 3, 4]


In [ ]:
img_size = 100                    #fix size
data = []                        #2 empty lists
target = []

for category in categories:
    folder_path = os.path.join(data_path,category)
    img_names = os.listdir(folder_path)
    
    for img_name in img_names:                              #pick 1 by 1
        img_path = os.path.join(folder_path,img_name)
        img = cv2.imread(img_path)                          #read image frm img_path
        
        try:
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)      #convert image to gray scale
            resized = cv2.resize(gray,(img_size,img_size))   #resizing the gray scale into 100*100
            data.append(resized)                             #append resized image to data
            target.append(label_dict[category])              #append to target, appending the image & the label(categorized) into the list(dataset) 
            
        except Exception as e:
            print('Exception:', e)                #if any exception raised, the exception will be printed here & pass to the next image        

In [ ]:
#normalize (convert to array 0-1)

import numpy as np

data = np.array(data)/255.0                                      #data & target convert to array
print(data.shape)
data = np.reshape(data,(data.shape[0],img_size,img_size,1))            # 1 - channel 
target = np.array(target)

from keras.utils import np_utils                  #np_utils --> string to array
new_target = np_utils.to_categorical(target)
print(new_target)

(413, 100, 100)
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


In [ ]:
new_target

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
np.save('data',data)                  #save data & target
np.save('target',new_target)